CREATE TABLE CATEGORIA_ITEM
(
    ID_CAT NUMBER(6) NOT NULL,
    DESCRIPCION VARCHAR(50) NOT NULL,
    CONSTRAINT "PK_CATEGORIA_ITEM_ID_CAT" PRIMARY KEY (ID_CAT),
    CONSTRAINT "UQ_CATEGORIA_ITEM_DESCRIPCION" UNIQUE (DESCRIPCION)
);

CREATE TABLE STAT_TYPE_ITEM
(
    ID_STAT NUMBER(6) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    CONSTRAINT "PK_STAT_ITEM_ID_STAT" PRIMARY KEY (ID_STAT),
    CONSTRAINT "UQ_STAT_ITEM_NOMBRE" UNIQUE (NOMBRE)
);

CREATE TABLE ITEM
(
    ID_ITEM NUMBER(6) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(50) NOT NULL,
    COD_CAT NUMBER(6) NOT NULL,
    CONSTRAINT "PK_ITEM_ID_ITEM" PRIMARY KEY (ID_ITEM),
    CONSTRAINT "FK_ITEM_COD_CAT" FOREIGN KEY (COD_CAT) REFERENCES CATEGORIA_ITEM(ID_CAT)
);

CREATE TABLE ITEM_STATS
(
    COD_ITEM NUMBER(6) NOT NULL,
    COD_STAT NUMBER(6) NOT NULL,
    VALOR NUMBER(6) NOT NULL,
    CONSTRAINT "PK_ITEM_STATS" PRIMARY KEY (COD_ITEM, COD_STAT),
    CONSTRAINT "FK_ITEM_STATS_COD_ITEM" FOREIGN KEY (COD_ITEM) REFERENCES ITEM(ID_ITEM),
    CONSTRAINT "FK_ITEM_STATS_COD_STAT" FOREIGN KEY (COD_STAT) REFERENCES STAT_TYPE_ITEM(ID_STAT)
);

CREATE SEQUENCE SEQ_ID_CATEGORIA
       MINVALUE 1
       MAXVALUE 999998
       START WITH 1
       INCREMENT BY 1
       ORDER;
       
CREATE SEQUENCE SEQ_ID_STAT_TYPE
       MINVALUE 1
       MAXVALUE 999998
       START WITH 1
       INCREMENT BY 1
       ORDER;

CREATE SEQUENCE SEQ_ID_ITEM
       MINVALUE 1
       MAXVALUE 999998
       START WITH 1
       INCREMENT BY 1
       ORDER;
